<a href="https://colab.research.google.com/github/nicholaspearson43/Advanced_Programming_Exam/blob/main/Deep%20Learning%20HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning AY 2021/22
## First compulsory assignment - Nicholas Pearson - SM3500457


## Q1
Build the Multilayer Perceptron (MLP) represented in the last image of the notebook using PT built-ins, with the assumptions written just below the image ("We suppose that...")
## A1

In [ ]:
import torch
import numpy as np

In [ ]:
class MLP(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.layer1=torch.nn.Linear(in_features=5, out_features=11, bias=False)
    self.layer2=torch.nn.Linear(in_features=11, out_features=16, bias=False)
    self.layer3=torch.nn.Linear(in_features=16, out_features=13, bias=False)
    self.layer4=torch.nn.Linear(in_features=13, out_features=8, bias=False)
    self.layer5=torch.nn.Linear(in_features=8, out_features=4, bias=False)

  def forward(self, X):
    out = self.layer1(X)
    out = torch.nn.functional.relu(out)
    out = self.layer2(out)
    out = torch.nn.functional.relu(out)
    out = self.layer3(out)
    out = torch.nn.functional.relu(out)
    out = self.layer4(out)
    out = torch.nn.functional.relu(out)
    out = self.layer5(out)
    out = torch.nn.functional.softmax(out)
    return out

## Q2
Provide calculation for the exact number of parameters of this MLP.
Do it first supposing that the layers don't have a bias term, then supposing that the bias is present wherever it's possible

##A2
No bias:
$(5 \cdot 11)+(11 \cdot 16)+(16\cdot13)+(13\cdot8)+(8\cdot4)=575$

With bias:
$(5 \cdot 11+11)+(11 \cdot 16+16)+(16\cdot13+13)+(13\cdot8+8)+(8\cdot4+4)=627$

## Q3
Calculate the L1 (vectorial) norm and the Frobenius norm for the params of each layer
## A3



In [ ]:
model = MLP()

In [ ]:
for param in model.parameters():
  print("L1 Norm:", torch.norm(param, 1).item())
  print("Frobenius Norm:", torch.norm(param, p='fro').item())

L1 Norm: 11.597103118896484
Frobenius Norm: 1.814905047416687
L1 Norm: 26.469280242919922
Frobenius Norm: 2.317514181137085
L1 Norm: 27.99208641052246
Frobenius Norm: 2.2081501483917236
L1 Norm: 14.560702323913574
Frobenius Norm: 1.6691266298294067
L1 Norm: 5.559162139892578
Frobenius Norm: 1.134905219078064


## Q4
Given 10 random datapoints, feed them into the network. This operation must be done all in one single command and must not make use of loops.
- Given the output of the network, using PyTorch code, find the class of assignment of each datapoint. This also must be done in a single PyTorch command without using loops.
- Drafting a vector of ground truths (whichever labels you like), provide code for the calculation of the accuracy
    - Tip: first get the number of correct assignments, then...

## A4

In [ ]:
y_hat = model(torch.rand((10,5)))
print(y_hat)

tensor([[0.2491, 0.2505, 0.2507, 0.2497],
        [0.2498, 0.2502, 0.2501, 0.2499],
        [0.2471, 0.2508, 0.2533, 0.2487],
        [0.2495, 0.2504, 0.2506, 0.2496],
        [0.2485, 0.2503, 0.2513, 0.2499],
        [0.2484, 0.2505, 0.2514, 0.2497],
        [0.2486, 0.2503, 0.2517, 0.2494],
        [0.2490, 0.2506, 0.2517, 0.2487],
        [0.2493, 0.2502, 0.2507, 0.2498],
        [0.2491, 0.2504, 0.2509, 0.2496]], grad_fn=<SoftmaxBackward0>)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


In [ ]:
y_class = torch.max(y_hat, dim=1).indices
print(y_class)

tensor([2, 1, 2, 2, 2, 2, 2, 2, 2, 2])


In [ ]:
y_true = torch.randint(0,4,(10,))
print(y_true)

tensor([0, 1, 0, 0, 2, 1, 2, 3, 0, 1])


In [ ]:
accuracy = torch.mean((y_true==y_class).float())
print(accuracy)

tensor(0.3000)
